import XCTest
@testable import WhoopStore

/// Phase 2c-2 Task 12 — cross-implementation codec pin, the Swift half. The Kotlin Backfiller
/// (Task 13) writes outbox blobs with `shared`'s `com.noop.ble.OutboxCodec`; this test proves the
/// Swift `RawOutbox` helpers decode a blob that codec produced (generated by the JVM
/// `Deflater(DEFAULT_COMPRESSION, nowrap = true)` actual — the Android-side encoder; the Apple-side
/// Kotlin actual calls the same Compression framework as Swift, so it is compatible by
/// construction). The mirror direction — Kotlin decoding a Swift/Apple-produced blob — is
/// `OutboxCodecTest.decodesSwiftProducedBlob_byteForByte` in `shared/src/commonTest`.
///
/// The assertion is cross-DECODABILITY of the pinned bytes, never encoder byte equality: DEFLATE
/// permits many valid encodings of the same payload (that both encoders happen to emit identical
/// bytes for this fixture today is a coincidence of shared zlib lineage, not a contract).
final class RawOutboxCrossImplTests: XCTestCase {

    /// Deterministic fixture frames — mirrored in `OutboxCodecTest.kt` and both blob generators:
    /// f1 = 104 bytes of `(i*31+7) & 0xFF`, f2 = empty, f3 = 300 bytes of `(i*7+3) & 0xFF`.
    private let fixtureFrames: [[UInt8]] = [
        (0..<104).map { UInt8(($0 * 31 + 7) & 0xFF) },
        [],
        (0..<300).map { UInt8(($0 * 7 + 3) & 0xFF) },
    ]

    /// `OutboxCodec.zlibCompressWithLength(OutboxCodec.packFrames(fixtureFrames))` as produced on
    /// the JVM (packed length 420).
    private let kotlinBlobHex =
        "a401000063666060c800627635d794e645071ffc97b38da99eb5f3c67731d390e2491b2fbce7d3f5c9ee5a79e239"
        + "9baa4b72d3c203f7ffc9da4457cddc71fd9ba84970d1c40de7dff1ea786775ae38fe8c55c539a971c1fe7b7f"
        + "65aca32a676cbff655c438a870c2fa736f79b4bd323b961f7bcaa2ec94d800b48a4187918181994b50425e4d"
        + "d7c4dac933203c2e35a7b8aab1a37fdadc25ab37ed3c70fcdcd53b8f5f7dfcf19f8d57445a49d3c0dcced527"
        + "382a3123bfacb6a57bd2cc05cbd76ddd73f8d4c51bf79fbdfdf29b8953405c4e55c7d8cad1c33f2c3625bba8"
        + "b2a1bd6fea9cc5ab36eed87fecec95db8f5e7ef8fe8f9547584a5143dfccd6c53b2832213dafb4a6b96be28c"
        + "f9cbd66ed97de8e485ebf79ebef9fc8b91835f4c5645dbc8d2c1dd2f342639abb0a2bead77caec452b376cdf"
        + "77f4cce55b0f5fbcfff697855b4852415dcfd4c6d92b30223e2db7a4baa973c2f4794bd76cde75f0c4f96b77"
        + "9fbcfef493819d4f544659cbd0c2decd37243a29b3a0bcaeb567f2ac852bd66fdb7be4f4a59b0f9ebffbfa87"
        + "14ff0300"

    private func bytes(_ s: String) -> Data {
        var out = [UInt8](); out.reserveCapacity(s.count / 2); var i = s.startIndex
        while i < s.endIndex {
            let j = s.index(i, offsetBy: 2)
            out.append(UInt8(s[i..<j], radix: 16)!); i = j
        }
        return Data(out)
    }

    func testDecodesKotlinProducedBlobByteForByte() throws {
        let payload = try WhoopStore.zlibDecompressWithLength(bytes(kotlinBlobHex))
        XCTAssertEqual(payload.count, 420, "packed length pinned by the generator")
        let frames = WhoopStore.unpackFrames(payload)
        XCTAssertEqual(frames.count, fixtureFrames.count)
        for (i, expected) in fixtureFrames.enumerated() {
            XCTAssertEqual(frames[i], expected, "frame \(i) differs")
        }
    }

    /// And the same bytes re-encoded by Swift still decode to the same frames — a guard against
    /// either helper drifting from the shared wire format.
    func testSwiftReEncodeOfFixtureRoundTrips() throws {
        let blob = try WhoopStore.zlibCompressWithLength(WhoopStore.packFrames(fixtureFrames))
        let frames = WhoopStore.unpackFrames(try WhoopStore.zlibDecompressWithLength(blob))
        XCTAssertEqual(frames, fixtureFrames)
    }
}
